### ISSUE TITLE
Question: using github packages authentication

### ISSUE THREAD

**Issue by tiagoqueiros** [Pixelmatters/eslint-config-pixelmatters#8]
Will this package require the usage of Github Packages and its authentication, for using the updated versions after 1.0.0?

![Setup step](https://cdn-std.droplr.net/files/acc_761601/sz9jIL)

The image refers to the setup configuration available for the [1.0.4](https://github.com/Pixelmatters/eslint-config-pixelmatters/packages/212965) release. This extra steps requires setting up Github tokens and configuring both the local machine and the pipeline - which can be a pain. 

![Pipeline error](https://cdn-std.droplr.net/files/acc_761601/Hu8ajS)

**Comment by gil0mendes** [comment]
Hey @tiagoqueiros 👋🏾 ,

No, this no longer requires any authentication to be installed. 

However, there was an issue with the GitHub workflow that published the package. I already fixed that issue, and a new one should be available at the NPM repository.

Closing due to be fixed on the latest release.
